### ISSUE TITLE
Challenge: What common problems can Relog solve? also, with what time complexity?

### ISSUE THREAD

**Issue by andrew-johnson-4** [andrew-johnson-4/InPlace#4]
[RosettaCode](https://rosettacode.org/wiki/Category:Solutions_by_Programming_Task), [Code Golf](https://code.golf/) etc. hav some programming problems which would be fun to try to solve with a non-turing-complete language.

The reduction rules at the heart of this are

$$reify \ bound \ var \ \ \frac{a↦B⊢a}{a⇻B⊢reify(B)}$$

and 

$$apply \ \ \frac{unify(f,fx)⊢r}{f⇻r⊢reify(apply(r))}$$

which locally delete each bound variable or function-case before entering any sort of recursive call. This effectively prevents divergence, but practically how much does this impact logic programming?

**Comment by andrew-johnson-4** [comment]
With the new features introduced today Relog could request a finite Turing machine and run that. So theoretically this creates a chicken-egg problem in applied vs theoretical strong-normalization.

**Comment by Richard5656** [comment]
I saw you stared my repository so I came here to check this out. 

From what I've looked at and read. Relog looks like a version of Thue mixed with Haskell but with more features. 

Not really understanding the notation here. Can you tell me more about that I'd be intrested in knowing more. Is this custom notation? Is there more documentation of Relog?

**Comment by andrew-johnson-4** [comment]
Relog is a notation for type system unifications. It is meant to be paired with PunC to create a basic programming system and formal basis for LSTS proofs. As such Relog is _not_ Turing Complete, it is strongly normalizing.

A simple example program in Relog would be parametered function application:

```
a=Int;Pair<a,a>
```

Here this program might represent applying a function `a -> Pair<a,a>` with a parameter `Int`. The result is expected to be `Pair<Int,Int>`.

A more complicated function application might be

```
Pair<a,b>=Pair<Int,Int>;b
```

Here this function might implement a function with the type signature `Pair<a,b> -> b` and it is being applied with argument `Pair<Int,Int>`.

I'll work on adding some documentation, but this is the motivation. I hope that helps.

**Comment by Richard5656** [comment]
Hmm ok so it's not Turing complete. I heard you needed a standard library. I'm good at writing those for low level systems. But I'd be intrested in learning what you had in mind for this. I've always wondered how a standard library would work for typed lambda calculus.

**Comment by andrew-johnson-4** [comment]
The standard library would be exposed through closed form unifications. I can handle setting up the unifications, the standard library would just need to provide some function calls that accept a number of RelogTerm's as arguments, do something, then return a RelogTerm.

For example `Print<"hello world">' could be implemented like following:

```rust
fn std_print(args: &[RelogTerm]) -> RelogTerm {
   for a in args {
      print!("{}", a);
   }
   RelogTerm::Atomic("0".to_string())
}
```

**Comment by andrew-johnson-4** [comment]
For reference, "closed form" is taken to mean that all argument terms will be in normal form. In lambda calculus there is no distinction between the concept of a Term `1 + 2` vs its normal form `3`. However for our use this reduction must happen _before_ being sent to a library function.

**Comment by Richard5656** [comment]
So what I'm getting from this is that it's something similar to a Haskell monad. Where you have something inside something. I will use (Inside) in an attempt to explain. 

So you have (1+2) and (3). Before you can send it to a library function you must evaluate it. first to get it to its normal form. In both cases 3. So you send it wrapped like so (3) and the library function takes 3 out and does the syscall or some other thing and then puts the result back in so like this (result) and returns it. () can represent relog terms.  


```Rust
fn std_print(args: &[RelogTerm]) -> RelogTerm {
   for a in args {
      print!("{}", a);
   }
   RelogTerm::Atomic("0".to_string())
}
```
I don't have alot of rust experience but I assume your code above takes a variable amount of RelogTerm's and prints them out and returns a RelogTerm Atomic of 0 to confirm everything went through fine.

**Comment by andrew-johnson-4** [comment]
Precisely. The only reason that I mention `1 + 2` vs `3` is that syscalls are only locally eager. The rest of the evaluation might be fairly lazy.

**Comment by Richard5656** [comment]
Relog is not a programing language but it's more like a finite state machine. That evaluates to a certain state. The state being a type. Looks a lot like BNF format mixed with Lambda Calculus now that I stare at it harder and that you've specified which part is an output. 

My knowledge of Relog according to your examples is very limited but isn't this Turing complete? I would assume you would be able to do Church encodings with this type system. 

https://en.wikipedia.org/wiki/Church_encoding

Oh you updated the front page. I'm sorry if i rushed you. I just wanted to know a little more about this since it looks interesting.

**Comment by andrew-johnson-4** [comment]
Not Turing Complete. If you find a way to escape that guarantee then file a bug.

Relog is a Term Rewriting System, similar to arithmetic but more generally useful. `1 +  2* 3 / 4` can't diverge, it only gets simpler and simpler until you get a final result. In our case types rewrite until you reach a concrete or normal form.

**Comment by andrew-johnson-4** [comment]
For comparison Lambda Calculus is also a Term Rewriting System but it can diverge.

A term like `(λy. y y) (λy. y y)` will keep rewriting into more and more complicated forms which is called divergence. This is where the specific rules for Relog reduction are important. These sort of programs should be impossible to represent as a Relog program.

**Comment by Richard5656** [comment]
Right because Lambda Calculus keeps expanding while Relog goes to a smaller more reduced form. 

I'm going to assume it's a Hindley–Milner type system.

I never understood these type systems. I've talked to some professors who urged me to look into type systems and functional programing but I've never inquired to know more. In my caveman mind I see float, ints, chars, pointers, and memory. Maybe a couple of structs or unions tossed around and that's what I would gravitate to. 

My question would be why would someone be interested in creating a type system this complicated?

I also want to know what you saw in those 2 repos you starred. They where what I considered some of my worst projects.

**Comment by andrew-johnson-4** [comment]
You don't have to be so self-deprecating. I think learning is cool even if that is all you get. I genuinely am interested in what people think about the current state of programming languages and why someone might want to make yet another new one. It is clear that we aren't in any final state yet, so it is important to look at what direction that people want to go into next.

Are you still interested in the subject of programming language design at all?

**Comment by Richard5656** [comment]
Yes I'm very intrested in programing language design mainly to compile to low level code. I want to optimize the semantics to make a readable yet simple and elegant language to be used to program microcontrollers and other such things. Without the hassle of using functional code which brings in a more convoluted way of handling side effects in my opinion. Concatenative languages is what I focus on the most currently. I'm currently working on a couple Forth like and C like languages. 

Sorry if I'm being self-deprecating. A lot of people have opposites views from me on what a good programing language should be. I feel that I'm in the minority with my opinions. 

I'm still very honored that a person of your caliber actually took interest in what I had to say. Thank you.

**Comment by andrew-johnson-4** [comment]
Optimization is great _if it is correct_. Making meaningful proofs of correctness is a productive line of thought that I am pursuing along with some of these projects. The specific syntax or semantics of whatever language is being used is irrelevant, the method of determining whether the optimization is 1) an improvement and 2) a correct transformation is what types can provide.

**Comment by Richard5656** [comment]
I think I'm seeing the picture. No matter how much syntatic sugar or metaprogramming I add. It's not expressive enough. 

To create an expressive language more advanced types are needed therefore we build up from primitive types. 

With more expression there is more room for error. Which is where your proofs come in to show correctness. 

Is that what you are explaining?

**Comment by andrew-johnson-4** [comment]
If it helps it helps. Many mathematicians refuse to use automated verification tools because they don't trust them. I am very pleased with the current direction of a few of these projects. I think they help me. That is all I can tell.

**Comment by Richard5656** [comment]
Anyways I really want to learn more about Relog. I'll be sure to star. Now that I can somewhat grasp your reasoning for this. I want to see where it goes. I might be able to contribute a standard library for unix syscalls in Rust. I've dumped equal amounts of time in hardware and operating systems design that I've dumped into programing language design. 

Not sure if you want a lower level interface or a more of a wrapper.

**Comment by andrew-johnson-4** [comment]
I wouldn't put too much effort into the library if you don't have to. The most important part is what you feel should be exposed, rather than how it is exposed. Just throwing in some calls to Rust standard library might be good enough.

Thanks for the interest! Welcome!
